#Имя workflow, которое будет отображаться в интерфейсе GitHub Actions
name: UI tests

# Указываем, когда будет запускаться данный workflow
on:
  push:
    branches:
      - main  # Запускать workflow, когда будет сделан коммит в ветку main
  pull_request:
    branches:
      - main  # Запускать workflow, когда будет сделан pull request в ветку main

# Определяем все шаги, которые должны быть выполнены в рамках работы с тестами
jobs:
  run-tests:
    runs-on: ubuntu-latest  # Указываем, что тесты будут запускаться на последней версии Ubuntu

    steps:
      # 1. Шаг, который будет клонировать репозиторий на машину GitHub Actions
      - name: Check out repository
        uses: actions/checkout@v3  # Используем GitHub Action для клонирования репозитория

      # 2. Шаг для установки Python на виртуальной машине
      - name: Set up Python
        uses: actions/setup-python@v4  # Используем GitHub Action для установки Python
        with:
          python-version: '3.11'  # Устанавливаем версию Python 3.13 (можно заменить на другую версию)

      # 3. Шаг для установки всех зависимостей проекта
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Обновляем pip до последней версии
          pip install -r requirements.txt  # Устанавливаем зависимости, указанные в requirements.txt
          playwright install --with-deps  # Устанавливаем браузеры для Playwright (если они не установлены)

      # 4. Шаг для запуска тестов с использованием pytest и генерации отчётов Allure
      - name: Run Playwright tests with pytest and generate Allure results
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses 4  # Запускаем тесты, отмеченные как "regression", генерируем результаты для Allure


      # 5. Шаг для сохранения результатов тестов как артефакт
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 1


  publish-report:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      # 1. Клонируем репозиторий
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Загружаем результаты тестов из артефакта
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: allure-results

      # 3. Получаем историю отчётов Allure с ветки gh-pages
      - name: Get Allure history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 4. Генерируем Allure отчет с историей
      - name: Generates Allure Report with history
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure_results
          allure_history: allure_history

      # 5. Деплоим отчет на GitHub Pages
      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history